Acq(0, bpm)
TriggerMux(0)
dbLoadTemplate("db/acq.substitutions", "P=${P1}, R=${R1}, ACQ_NAME=GEN, NELM=${NELM}, INDEX=0")
dbLoadTemplate("db/pbpm_data.substitutions", "P=${P1}, R=${R1}, ACQ_NAME=GEN, NELM=${NELM}, PORT=ACQ-0")
Acq(1, bpm)
TriggerMux(1)
dbLoadTemplate("db/acq.substitutions", "P=${P2}, R=${R2}, ACQ_NAME=GEN, NELM=${NELM}, INDEX=1")
dbLoadTemplate("db/pbpm_data.substitutions", "P=${P2}, R=${R2}, ACQ_NAME=GEN, NELM=${NELM}, PORT=ACQ-1")

Acq(2, bpm)
TriggerMux(2)
dbLoadTemplate("db/acq.substitutions", "P=${P1}, R=${R1}, ACQ_NAME=PM, NELM=${NELM}, INDEX=2")
dbLoadTemplate("db/pbpm_data.substitutions", "P=${P1}, R=${R1}, ACQ_NAME=PM, NELM=${NELM}, PORT=ACQ-2")
Acq(3, bpm)
TriggerMux(3)
dbLoadTemplate("db/acq.substitutions", "P=${P2}, R=${R2}, ACQ_NAME=PM, NELM=${NELM}, INDEX=3")
dbLoadTemplate("db/pbpm_data.substitutions", "P=${P2}, R=${R2}, ACQ_NAME=PM, NELM=${NELM}, PORT=ACQ-3")
